// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKTlTHQmS0l9uN5Jrvqgv422rDo1X4j1w',
    appId: '1:1057277109448:android:27e9451c1a1baba0ac71fd',
    messagingSenderId: '1057277109448',
    projectId: 'frndschat-a9079',
    storageBucket: 'frndschat-a9079.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmnTkRRZb50z0ctC9LrpmpRqDIHvNXZ3E',
    appId: '1:1057277109448:ios:619b1d2453e87a53ac71fd',
    messagingSenderId: '1057277109448',
    projectId: 'frndschat-a9079',
    storageBucket: 'frndschat-a9079.appspot.com',
    androidClientId: '1057277109448-fdkkk06587hj3m741p34i1fr7d6k9nc1.apps.googleusercontent.com',
    iosClientId: '1057277109448-45tgli1raja6a428t6rrp4t102jemkqt.apps.googleusercontent.com',
    iosBundleId: 'com.example.frndsChat',
  );
}
